
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

logger:
  default: info

zwave:
   usb_path: /dev/ttyACM0

# this is connected to the GeoVision Mobile Server
camera:
  - platform: mjpeg
    name: GeoVision Matrix
    mjpeg_url: http://192.168.0.15:8080/jpeg?cam=65

frontend:
  themes: !include_dir_merge_named themes

# load the ui config from ui-lovelace.yaml
lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Earth Ship

binary_sensor:
  - platform: template
    sensors:
      sun_up:
        friendly_name: "Sun is up"
        value_template: >-
          {{ state_attr('sun.sun', 'elevation')|float > 0 }}
      kitchen_motion:
        friendly_name: "Kitchen motion"
        device_class: motion
        value_template: >-
          {{ states('sensor.aeon_labs_zw100_multisensor_6_burglar')|float > 0 }}

homeassistant:
  customize:
    binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3:
      sensor_class: opening
    binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4:
      sensor_class: opening

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
