# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

logger:
  default: info

zwave:
   usb_path: /dev/ttyACM0

# this is connected to the GeoVision Mobile Server
camera:
  - platform: mjpeg
    name: GeoVision Matrix
    mjpeg_url: http://192.168.0.15:8080/jpeg?cam=65
  - platform: mjpeg
    name: Lawn
    mjpeg_url: http://192.168.0.15:8080/jpeg?cam=2
  - platform: mjpeg
    name: Pond
    mjpeg_url: http://192.168.0.15:8080/jpeg?cam=3
  - platform: mjpeg
    name: Driveway
    mjpeg_url: http://192.168.0.15:8080/jpeg?cam=4
  - platform: mjpeg
    name: Backyard
    mjpeg_url: http://192.168.0.15:8080/jpeg?cam=5
  - platform: mjpeg
    name: Front Door
    mjpeg_url: http://192.168.0.15:8080/jpeg?cam=6

frontend:
  themes: !include_dir_merge_named themes

# load the ui config from ui-lovelace.yaml
lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    name: Earth Ship

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

