# from `sensor:`

# https://community.home-assistant.io/t/sun-values-not-valid/89398/2
- platform: template
  sensors:
    # Sunset & Sunrise
    next_sunrise:
      friendly_name: Sunrise
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
    next_sunset:
      friendly_name: Sunset
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
    solar_angle:
      friendly_name: "Sun angle"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"

- platform: template
  sensors:
    kitchen_door:
      value_template: >-
        {% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3.state == 'on' %}
          Open
        {% elif states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3.state == 'off' %}
          Closed
        {% else %}
          n/a
        {% endif %}
      icon_template: >
        {% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3.state == 'on' %}
          mdi:door-open
        {% elif states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3.state == 'off' %}
          mdi:door-closed
        {% else %}
          mdi:help
        {% endif %} 

- platform: template
  sensors:
    porch_door:
      value_template: >-
        {% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4.state == 'on' %}
          Open
        {% elif states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4.state == 'off' %}
          Closed
        {% else %}
          n/a
        {% endif %}
      icon_template: >
        {% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4.state == 'on' %}
          mdi:door-open
        {% elif states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4.state == 'off' %}
          mdi:door-closed
        {% else %}
          mdi:help
        {% endif %} 
