# from `sensor:`

# https://community.home-assistant.io/t/sun-values-not-valid/89398/2
- platform: template
  sensors:
    # Sunset & Sunrise
    next_sunrise:
      friendly_name: Sunrise
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
    next_sunset:
      friendly_name: Sunset
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
    solar_angle:
      friendly_name: "Sun angle"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"

- platform: template
  sensors:
    kitchen_door_status:
      value_template: '{% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3 %}
        {% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3 == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Kitchen Door'

- platform: template
  sensors:
    porch_door_status:
      value_template: '{% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4 %}
        {% if states.binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4 == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Porch Door'
