title: Earth Ship

resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module

custom_header:
  compact_mode: true
  options_hide: true
#  kiosk_mode: true # completely hides to header: you can add ?disable_ch to the url to get it back
#  footer_mode: true

views:
#  - badges:
#      - entity: binary_sensor.updater
#      - entity: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
#      - entity: person.andy
#      - entity: sensor.plex_oahu
#      - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
#      - entity: sensor.aeon_labs_zw100_multisensor_6_luminance
#      - entity: sensor.aeon_labs_zw100_multisensor_6_relative_humidity
#      - entity: sensor.aeon_labs_zw100_multisensor_6_ultraviolet
#      - entity: sensor.aeon_labs_zw100_multisensor_6_sourcenodeid
#      - entity: sensor.aeon_labs_zw100_multisensor_6_burglar
#      - entity: sensor.aeon_labs_zw100_multisensor_6_battery_level
#      - entity: sun.sun
  - cards:
      - entity: weather.earth_ship
        type: weather-forecast

#      - detail: 2
#        entity: sensor.aeon_labs_zw100_multisensor_6_temperature
#        graph: line
#        hours_to_show: 48
#        name: Home Temperature
#        type: sensor

      # https://github.com/kalkih/mini-graph-card

      - type: custom:mini-graph-card
        entities:
          - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
            name: Temperature
          - entity: sun.sun
            color: gray
            name: Night
            show_line: false
            show_points: false
            show_legend: false
            y_axis: secondary
        name: Temperature
        # hours_to_show: 168
        # points_per_hour: 0.25
        show:
          labels: true
          labels_secondary: true

      # https://github.com/kalkih/mini-graph-card

      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.aeon_labs_zw100_multisensor_6_relative_humidity
            line_color: blue
            line_width: 8
            font_size: 75
            name: Humidity
          - type: custom:mini-graph-card
            entities:
              - sensor.aeon_labs_zw100_multisensor_6_luminance
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
            name: Light
          - type: custom:mini-graph-card
            entities:
              - sensor.aeon_labs_zw100_multisensor_6_ultraviolet
            line_color: var(--accent-color)
            line_width: 8
            font_size: 75
            name: UV

      - aspect_ratio: 0%
        camera_image: camera.geovision_matrix
        camera_view: live
        entities: []
        entity: camera.geovision_matrix
        image: 'https://www.home-assistant.io/images/merchandise/shirt-frontpage.png'
        title: Security Cameras
        type: picture-glance
      - entity: media_player.plex_tv_un55nu8000
        type: media-control
      - entities:
          - zwave.aeon_labs_zw090_z_stick_gen5_us
          - zwave.aeon_labs_zw100_multisensor_6
          - zwave.unknown_node_6
        title: Z-Wave
        type: entities
      - type: 'custom:home-feed-card' # https://github.com/gadgetchnnel/lovelace-home-feed-card
        title: Home Feed
        show_empty: true
        id_filter: ^home_feed_.*
        entities:
          - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
            # name: Me
            include_history: true
            max_history: 5
            # remove_repeats: false
          - entity: weather.earth_ship
          - entity: sun.sun
    path: default_view
    title: Home

