title: Earth Ship

resources:
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: js
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-darksky-card/lovelace-darksky-card.js
    type: js

custom_header:
  compact_mode: true
  options_hide: true
#  kiosk_mode: true # completely hides to header: you can add ?disable_ch to the url to get it back
#  footer_mode: true

views:
  - path: default_view
    title: Home
    panel: true
    cards:
      - type: vertical-stack
        cards:
        - aspect_ratio: 0%
          camera_image: camera.geovision_matrix
          camera_view: live
          entities: []
          entity: camera.geovision_matrix
          image: 'https://www.home-assistant.io/images/merchandise/shirt-frontpage.png'
          title: Security Cameras
          type: picture-glance

        - type: horizontal-stack
          cards:
            - type: custom:lovelace-darksky-card
              entity_current_conditions: sensor.dark_sky_icon
              entity_temperature: sensor.dark_sky_temperature
              entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
              entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
              entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
              entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
              entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
              entity_forecast_icon_1: sensor.dark_sky_icon_1d
              entity_forecast_icon_2: sensor.dark_sky_icon_2d
              entity_forecast_icon_3: sensor.dark_sky_icon_3d
              entity_forecast_icon_4: sensor.dark_sky_icon_4d
              entity_forecast_icon_5: sensor.dark_sky_icon_5d
              entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0d
              entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1d
              entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2d
              entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3d
              entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4d
              entity_summary_1: sensor.dark_sky_summary_1d
              entity_summary_2: sensor.dark_sky_summary_2d
              entity_summary_3: sensor.dark_sky_summary_3d
              entity_summary_4: sensor.dark_sky_summary_4d
              entity_summary_5: sensor.dark_sky_summary_5d
              entity_sun: sun.sun
              entity_visibility: sensor.dark_sky_visibility
              entity_daytime_high: sensor.dark_sky_daytime_high_temperature_0d
              entity_wind_bearing: sensor.dark_sky_wind_bearing
              entity_wind_speed: sensor.dark_sky_wind_speed
              entity_humidity: sensor.dark_sky_humidity
              entity_pressure: sensor.dark_sky_pressure
              entity_apparent_temp: sensor.dark_sky_apparent_temperature
              entity_daily_summary: sensor.dark_sky_daily_summary
              entity_pop: sensor.dark_sky_precip_probability
              entity_pop_intensity: sensor.dark_sky_precip_intensity
              entity_pop_1: sensor.dark_sky_precip_probability_1d
              entity_pop_2: sensor.dark_sky_precip_probability_2d
              entity_pop_3: sensor.dark_sky_precip_probability_3d
              entity_pop_4: sensor.dark_sky_precip_probability_4d
              entity_pop_5: sensor.dark_sky_precip_probability_5d
            - type: vertical-stack
              cards:
                - type: glance
                  title: Doors
                  columns: 2
                  entities:
                    - entity: sensor.kitchen_door
                      name: Kitchen Door
                      show_state: false
                      show_last_changed: true
                    - entity: sensor.porch_door
                      name: Porch Door
                      show_state: false
                      show_last_changed: true
                - type: 'custom:home-feed-card' # https://github.com/gadgetchnnel/lovelace-home-feed-card
                  title: Home Feed
                  show_empty: true
                  id_filter: ^home_feed_.*
                  max_item_count: 7
                  compact_mode: true
                  entities:
                    - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
                      # name: Me
                      include_history: false
                      # max_history: 5
                      remove_repeats: true
                      more_info_on_tap: true
                    - entity: weather.earth_ship
                    - entity: sun.sun
                    - entity: sensor.kitchen_door
                      name: Kitchen Door
                    - entity: sensor.porch_door
                      name: Porch Door
                    - entity: binary_sensor.kitchen_motion

        - type: horizontal-stack
          cards:
#          - type: vertical-stack
#            cards:
#              - type: weather-forecast            
#                entity: weather.earth_ship
          - type: vertical-stack
            cards:
            - type: custom:mini-graph-card
              name: Local Barometer
              hours_to_show: 168
              entities:
                - entity: sensor.local_barometric_pressure
                  name: Barometric Pressure
            - type: custom:mini-graph-card
              entities:
                - entity: sensor.snake_river_temp
            - type: custom:mini-graph-card
              name: Outside Temperature
              hours_to_show: 168
              points_per_hour: 0.1
              hour24: true
              group_by: date
              entities:
                - entity: sensor.local_temperature
                  aggregate_func: max
                  name: Max
                  color: #e74c3c
                - entity: sensor.local_temperature
                  aggregate_func: min
                  name: Min
                - entity: sensor.local_temperature
                  aggregate_func: avg
                  name: Avg
                  color: green

          - type: vertical-stack
            cards:
            # https://github.com/kalkih/mini-graph-card
            - type: custom:mini-graph-card
              lower_bound: 0
              entities:
                - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
                  name: Inside
                  line_width: 8
                  show_legend: false
                - entity: sensor.local_temperature
                  name: Outside
                  line_width: 4
                  show_legend: false
              show:
                # extrema: true
                legend: false
              name: Temperature
              hours_to_show: 72
            - type: custom:mini-graph-card
              lower_bound: 0
              entities:
                - entity: sensor.aeon_labs_zw100_multisensor_6_relative_humidity
                  name: Inside
                  show_legend: false
                - entity: sensor.local_humidity
                  name: Outside
                  line_width: 4
                  show_legend: false
              show:
                labels: true
                legend: false
              name: Humidity
              hours_to_show: 72

#        # https://github.com/kalkih/mini-graph-card
#        - type: custom:mini-graph-card
#          entities:
#            - entity: binary_sensor.kitchen_motion
#              name: Living room
#              color: var(--accent-color)
#          name: Motion last hour
#          hours_to_show: 1
#          points_per_hour: 60
#          update_interval: 30
#          aggregate_func: max
#          line_width: 2
#          smoothing: false
#          state_map:
#            - value: "off"
#              label: Clear
#            - value: "on"
#              label: Detected

#          - type: custom:mini-graph-card
#            entities:
#              - sensor.aeon_labs_zw100_multisensor_6_luminance
#            line_color: '#e74c3c'
#            line_width: 8
#            font_size: 75
#            name: Light
#          - type: custom:mini-graph-card
#            entities:
#              - sensor.aeon_labs_zw100_multisensor_6_ultraviolet
#            line_color: var(--accent-color)
#            line_width: 8
#            font_size: 75
#            name: UV

#        - entity: media_player.plex_tv_un55nu8000
#          type: media-control

#        - type: media-control
#          entity: media_player.sunroom_speaker

  #      - entities:
  #          - zwave.aeon_labs_zw090_z_stick_gen5_us
  #          - zwave.aeon_labs_zw100_multisensor_6
  #          - zwave.unknown_node_6
  #          - zwave.unknown_node_7
  #        title: Z-Wave
  #        type: entities

  - path: weather
    title: Weather
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: iframe
            url: https://embed.windy.com/embed2.html?lat=46.671&lon=-117.506&zoom=11&level=surface&overlay=wind&menu=&message=&marker=&calendar=12&pressure=&type=map&location=coordinates&detail=true&detailLat=46.671&detailLon=-117.506&metricWind=mph&metricTemp=%C2%B0F&radarRange=-1
            # <iframe width="650" height="450" src="https://embed.windy.com/embed2.html?lat=46.629&lon=-117.506&zoom=11&level=surface&overlay=wind&menu=&message=&marker=&calendar=12&pressure=&type=map&location=coordinates&detail=true&detailLat=46.671&detailLon=-117.506&radarRange=-1" frameborder="0"></iframe>
            aspect_ratio: 90%
          - type: custom:mini-graph-card
            name: Wind Speed
            lower_bound: 0
            upper_bound: 30
            hours_to_show: 48
            entities:
              - entity: sensor.local_wind_speed
                name: Wind Speed
            color_thresholds:
              - value: 10
                color: "#aaffaa"
              - value: 15
                color: "#33ff33"
              - value: 22
                color: "#ff3333"
          - type: custom:mini-graph-card
            name: Wind Angle
            lower_bound: 0
            upper_bound: 360
            hours_to_show: 48
            entities:
              - entity: sensor.local_wind_bearing
                name: Wind Angle
                show_line: false
                show_points: true
                show_legend: false



  - path: camera
    title: Cameras
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - aspect_ratio: 4:3
            camera_image: camera.lawn
            camera_view: live
            entities: []
            entity: camera.lawn
            title: Lawn
            type: picture-glance
          - aspect_ratio: 4:3
            camera_image: camera.pond
            camera_view: live
            entities: []
            entity: camera.pond
            title: Pond
            type: picture-glance
          - aspect_ratio: 16:9
            camera_image: camera.porch
            camera_view: live
            entities: []
            entity: camera.porch
            title: Front Door
            type: picture-glance
          - aspect_ratio: 16:9
            camera_image: camera.front_door
            camera_view: live
            entities: []
            entity: camera.front_door
            title: Front Door
            type: picture-glance
          - aspect_ratio: 4:3
            camera_image: camera.driveway
            camera_view: live
            entities: []
            entity: camera.driveway
            title: Driveway
            type: picture-glance
          - aspect_ratio: 4:3
            camera_image: camera.backyard
            camera_view: live
            entities: []
            entity: camera.backyard
            title: Backyard
            type: picture-glance

  - path: other
    title: Other
    cards:
      - detail: 2
        entity: sensor.aeon_labs_zw100_multisensor_6_temperature
        graph: line
        hours_to_show: 48
        name: Home Temperature
        type: sensor
      - type: entities
        title: Sun
        show_header_toggle: false
        entities:
          - entity: sun.sun
          - entity: sensor.next_sunrise
            name: "Next Sunrise:"
            icon: mdi:weather-sunset-up
          - entity: sensor.next_sunset
            name: "Next Sunset:"
            icon: mdi:weather-sunset-down
          - entity: sensor.solar_angle
            name: "Sun Angle:"
            icon: mdi:angle-acute

    badges:
      - entity: binary_sensor.updater
#      - entity: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
      - entity: person.andy
#      - entity: sensor.plex_oahu
      - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
      - entity: sensor.aeon_labs_zw100_multisensor_6_luminance
      - entity: sensor.kitchen_door
      - entity: sensor.porch_door
      - entity: binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3
      - entity: binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4
      - entity: sensor.aeon_labs_zw100_multisensor_6_ultraviolet
#      - entity: sensor.aeon_labs_zw100_multisensor_6_sourcenodeid
      - entity: sensor.aeon_labs_zw100_multisensor_6_burglar
#      - entity: sensor.aeon_labs_zw100_multisensor_6_battery_level
      - entity: sun.sun

  - path: network
    title: Network
    badges: []
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.wan
          - entity: binary_sensor.gateway
        show_header_toggle: false
        title: Network
      - type: glance
        entities:
          - entity: sensor.uptime
            name: HA Uptime
          - entity: sensor.server_uptime
            name: Server Uptime
        theme: default
        title: Server
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.c3000_100nas_gateway_kb_sec_received
            name: kB Received
          - entity: sensor.c3000_100nas_gateway_kb_sec_sent
            name: kB Sent
        name: Internet
        hours_to_show: 48
      - type: horizontal-stack
        cards:
        - entity: sensor.processor_use
          max: 100
          min: 0
          name: CPU
          severity:
            green: 0
            red: 90
            yellow: 50
          theme: default
          type: gauge
        - entity: sensor.memory_use_percent
          max: 100
          min: 0
          name: Memory
          severity:
            green: 0
            red: 90
            yellow: 50
          theme: default
          type: gauge
      - entity: sensor.load_1m
        type: gauge
      - type: horizontal-stack
        cards:
          - entity: sensor.disk_read
            type: gauge
          - entity: sensor.disk_write
            type: gauge
