title: Earth Ship

resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module

custom_header:
  compact_mode: true
  options_hide: true
#  kiosk_mode: true # completely hides to header: you can add ?disable_ch to the url to get it back
#  footer_mode: true

views:
  - path: default_view
    title: Home
    panel: true
    cards:
      - type: vertical-stack
        cards:

        - aspect_ratio: 0%
          camera_image: camera.geovision_matrix
          camera_view: live
          entities: []
          entity: camera.geovision_matrix
          image: 'https://www.home-assistant.io/images/merchandise/shirt-frontpage.png'
          title: Security Cameras
          type: picture-glance

        - type: horizontal-stack
          cards:
          - type: glance
            title: Doors
            columns: 1
            entities:
              - entity: sensor.kitchen_door
                name: Kitchen Door
                show_state: false
                show_last_changed: true
              - entity: sensor.porch_door
                name: Porch Door
                show_state: false
                show_last_changed: true

          - type: 'custom:home-feed-card' # https://github.com/gadgetchnnel/lovelace-home-feed-card
            title: Home Feed
            show_empty: true
            id_filter: ^home_feed_.*
            max_item_count: 7
            compact_mode: true
            entities:
              - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
                # name: Me
                include_history: false
                # max_history: 5
                remove_repeats: true
                more_info_on_tap: true
              - entity: weather.earth_ship
              - entity: sun.sun
              - entity: sensor.kitchen_door
                name: Kitchen Door
              - entity: sensor.porch_door
                name: Porch Door
              - entity: binary_sensor.kitchen_motion

        - type: horizontal-stack
          cards:
          - entity: weather.earth_ship
            type: weather-forecast
          - type: entities
            title: Sun
            entities:
              - entity: sun.sun
              - entity: sensor.next_sunrise
                name: "Next Sunrise:"
                icon: mdi:weather-sunset-up
              - entity: sensor.next_sunset
                name: "Next Sunset:"
                icon: mdi:weather-sunset-down
              - entity: sensor.solar_angle
                name: "Sun Angle:"
                icon: mdi:angle-acute

          - type: vertical-stack
            cards:
            # https://github.com/kalkih/mini-graph-card
            - type: custom:mini-graph-card
              entities:
                - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
                  name: Temperature
              name: Temperature
              hours_to_show: 72
              # points_per_hour: 0.25
              show:
                labels: true
                labels_secondary: true
            - type: custom:mini-graph-card
              entities:
                - sensor.aeon_labs_zw100_multisensor_6_relative_humidity
              line_color: blue
              line_width: 8
              font_size: 75
              name: Humidity

#        # https://github.com/kalkih/mini-graph-card
#        - type: custom:mini-graph-card
#          entities:
#            - entity: binary_sensor.kitchen_motion
#              name: Living room
#              color: var(--accent-color)
#          name: Motion last hour
#          hours_to_show: 1
#          points_per_hour: 60
#          update_interval: 30
#          aggregate_func: max
#          line_width: 2
#          smoothing: false
#          state_map:
#            - value: "off"
#              label: Clear
#            - value: "on"
#              label: Detected

#          - type: custom:mini-graph-card
#            entities:
#              - sensor.aeon_labs_zw100_multisensor_6_luminance
#            line_color: '#e74c3c'
#            line_width: 8
#            font_size: 75
#            name: Light
#          - type: custom:mini-graph-card
#            entities:
#              - sensor.aeon_labs_zw100_multisensor_6_ultraviolet
#            line_color: var(--accent-color)
#            line_width: 8
#            font_size: 75
#            name: UV

        - entity: media_player.plex_tv_un55nu8000
          type: media-control

        - type: media-control
          entity: media_player.sunroom_speaker

        - type: custom:mini-graph-card
          entities:
            - entity: sensor.c3000_100nas_gateway_kb_sec_received
              name: kB Received
            - entity: sensor.c3000_100nas_gateway_kb_sec_sent
              name: kB Sent
          name: Internet
          hours_to_show: 48

  #      - entities:
  #          - zwave.aeon_labs_zw090_z_stick_gen5_us
  #          - zwave.aeon_labs_zw100_multisensor_6
  #          - zwave.unknown_node_6
  #          - zwave.unknown_node_7
  #        title: Z-Wave
  #        type: entities

  - path: other
    title: Other
    cards:
      - detail: 2
        entity: sensor.aeon_labs_zw100_multisensor_6_temperature
        graph: line
        hours_to_show: 48
        name: Home Temperature
        type: sensor
    badges:
      - entity: binary_sensor.updater
#      - entity: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
      - entity: person.andy
#      - entity: sensor.plex_oahu
      - entity: sensor.aeon_labs_zw100_multisensor_6_temperature
      - entity: sensor.aeon_labs_zw100_multisensor_6_luminance
      - entity: sensor.kitchen_door
      - entity: sensor.porch_door
      - entity: binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_3
      - entity: binary_sensor.homeseer_technologies_unknown_type_0201_id_0008_sensor_4
      - entity: sensor.aeon_labs_zw100_multisensor_6_ultraviolet
#      - entity: sensor.aeon_labs_zw100_multisensor_6_sourcenodeid
      - entity: sensor.aeon_labs_zw100_multisensor_6_burglar
#      - entity: sensor.aeon_labs_zw100_multisensor_6_battery_level
      - entity: sun.sun
